version: '3.8'

services:
  # Drupal development server
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    command: docker-as-wait db:3306 -- docker-as-drupal apache-server
    depends_on:
      - db
    environment:
      APP_ENV: development
      BASE_URL: http://localhost
      DATABASE_URL: mysql://drupal:drupal@db/drupal_development
      HOME: /var/www
    restart: "no"
    volumes:
      - backups:/var/backups
      # - ./patches:/var/www/patches
      # Drupal
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      # Drupal Modules
      # - ./web/modules/custom:/var/www/web/modules/custom
      - ./web/sites/default/settings.development.php:/var/www/web/sites/default/settings.development.php
      # Files
      - ./web/sites/default/files:/var/www/web/sites/default/files

  # Database
  db:
    image: mariadb:10.4
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal_%
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
  backups:
